### ISSUE TITLE
server crashes on update

### ISSUE THREAD

**Issue by soupdiver** [legalthings/mongodb-rest#40]
When performing a `PUT` on a document the server always crashes with

```
TypeError: Cannot read property '_id' of undefined
    at ... /mongodb-rest/lib/rest.js:138:68
    at ... /mongodb-rest/node_modules/mongodb/lib/mongodb/collection/core.js:572:7
    at ... /mongodb-rest/node_modules/mongodb/lib/mongodb/db.js:1131:7
    at ... /mongodb-rest/node_modules/mongodb/lib/mongodb/db.js:1847:9
    at Server.Base._callHandler (... /mongodb-rest/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
    at ... /mongodb-rest/node_modules/mongodb/lib/mongodb/connection/server.js:478:18
    at MongoReply.parseBody (... /mongodb-rest/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (... /mongodb-rest/node_modules/mongodb/lib/mongodb/connection/server.js:436:20)
    at emit (events.js:95:17)
    at null.<anonymous> (... /mongodb-rest/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)

```

**Comment by Minstel** [comment]
@soupdiver I do not see it chashing, so it's probably fixed already.
